name: macro_host
publish-to: none

environment:
  sdk: ^3.6.0-0

dependencies:
  analyzer: any
  dart_model: any
  dart_model_analyzer_service: any
  macro_protocol: any
  stream_transform: ^2.1.0

dependency_overrides:
  dart_model:
    path: ../dart_model
  dart_model_analyzer_service:
    path: ../dart_model_analyzer_service
  macro_protocol:
    path: ../macro_protocol
